apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:  # No host specified - will match any host
        paths:
          - path: /dataSaver
            pathType: Prefix
            backend:
              service:
                name: datasaver-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: searchquery-service
                port:
                  number: 80